# docker-compose.yml for travis ci testing
version: '3.1'
services:
  mysql:
    restart: always
    image: mysql:5.7
    command: ['mysqld','--character-set-server=utf8mb4']
    environment:
      MYSQL_ROOT_PASSWORD: root
  openemr:
    restart: always
    image: openemr/openemr:flex-3.12
    ports:
    - 80:80
    - 443:443
    volumes:
    - ../../:/var/www/localhost/htdocs/openemr
    environment:
      FORCE_NO_BUILD_MODE: "yes"
      EMPTY: "yes"
    depends_on:
    - mysql
