name: Validate codecov.yml

on:
  pull_request:
    paths:
    - codecov.yml
  push:
    paths:
    - codecov.yml

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name == 'pull_request' && github.event.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  validate-codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Validate codecov.yml
        run: curl -f -X POST --data-binary @codecov.yml https://codecov.io/validate
